### ISSUE TITLE
while reloading postgres java hangs

### ISSUE THREAD

**Issue by MelanieGault** [atris/JDBC_FDW#18]
Hi,

I use your module since a long time and everything works fine. Tanks a lot !

But recently I have a new app which use JDBC FDW very frequently.
At each reload of postgres (SIGHUP) the postmaster process forward SIGHUP to every child. And the JAVA one considers this signal as a abnormal terminaison, and stops immediatly.
As a consequence the postmaster goes into recovery mode because of a crash of one of his child.

I see that -Xrs option passed to the JVM will change that behaviour, but I dont see anything in possible options.

How do you manage that case ?
thanks

Melanie

**Comment by atris** [comment]
Hi!

I can add the case as an option to the JVM (See where JVM options are passed to JVM). Please feel free to add a patch for it though!

**Comment by MelanieGault** [comment]
Hi,

OK thanks for your answer.
I'm not good enough in C language to do it by myself.
