### ISSUE TITLE
Error JDBCUtilsClass is NULL

### ISSUE THREAD

**Issue by theRealZing** [atris/JDBC_FDW#9]
linux 64 (centOS) , postgres 9.2.1.  Followed instructions in README - all went fine with no error messages up to the point of selecting data from the newly created foreign table.  Server log and psql both show: "ERROR:  JDBCUtilsClass is NULL".  Any idea what is wrong?

**Comment by jekor** [comment]
For anyone else facing this issue: note that the extension takes the value of pkglibdir *at compile time*, not at runtime. This creates problems for systems like NixOS where the pkglibdir is handed to PostgreSQL via systemd because it is not known at compile time.

**Comment by zhihuiFan** [comment]
> For anyone else facing this issue: note that the extension takes the value of pkglibdir _at compile time_, not at runtime. This creates problems for systems like NixOS where the pkglibdir is handed to PostgreSQL via systemd because it is not known at compile time.

I would suggest people read the above comments clearly,  I think that should be the root cause for many case.  If you don't know what value is used at compile time, try `strings jdbc_fdw.so | grep PKG_LIB_DIR`

**Comment by math-g** [comment]
In my case, I resolved this error simply by setting correct permissions for user postgres on `PGK_LIBDIR/JDBCDriverLoader.class` and `PGK_LIBDIR/JDBCUtils.class`.
Only root had read permissions on them after make install.
